#!/bin/bash 

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --gpus-per-node=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=02:30:00
#SBATCH --output=%x-%j.out

set -e

PROJECT_DIR="$PWD"
cd $PROJECT_DIR

module purge
module load 2022
module load Mamba/4.14.0-0
module load CUDA/11.8.0

source activate .env/


export PYTHONPATH=${PROJECT_DIR}:$PYTHONPATH

python eval_ALMA_smooth_8bit.py "$@"